/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyToolsRouteImport } from './routes/study-tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeTestRouteImport } from './routes/practice-test'
import { Route as PlcRouteImport } from './routes/plc'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ExamPrepRouteImport } from './routes/exam-prep'
import { Route as DataCenterRouteImport } from './routes/data-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as DevMotorCalcsRouteImport } from './routes/dev.motor-calcs'
import { Route as CoursesTradeRouteImport } from './routes/courses.$trade'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as ApiParseL5xRouteImport } from './routes/api/parse-l5x'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicShareTokenRouteImport } from './routes/api/public/share.$token'

const StudyToolsRoute = StudyToolsRouteImport.update({
  id: '/study-tools',
  path: '/study-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTestRoute = PracticeTestRouteImport.update({
  id: '/practice-test',
  path: '/practice-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PlcRoute = PlcRouteImport.update({
  id: '/plc',
  path: '/plc',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPrepRoute = ExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCenterRoute = DataCenterRouteImport.update({
  id: '/data-center',
  path: '/data-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMotorCalcsRoute = DevMotorCalcsRouteImport.update({
  id: '/dev/motor-calcs',
  path: '/dev/motor-calcs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesTradeRoute = CoursesTradeRouteImport.update({
  id: '/courses/$trade',
  path: '/courses/$trade',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseL5xRoute = ApiParseL5xRouteImport.update({
  id: '/api/parse-l5x',
  path: '/api/parse-l5x',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareTokenRoute = ApiPublicShareTokenRouteImport.update({
  id: '/api/public/share/$token',
  path: '/api/public/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-center': typeof DataCenterRoute
  '/exam-prep': typeof ExamPrepRoute
  '/mcp': typeof McpRoute
  '/plc': typeof PlcRoute
  '/practice-test': typeof PracticeTestRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-tools': typeof StudyToolsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/parse-l5x': typeof ApiParseL5xRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/courses/$trade': typeof CoursesTradeRoute
  '/dev/motor-calcs': typeof DevMotorCalcsRoute
  '/share/$token': typeof ShareTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-center': typeof DataCenterRoute
  '/exam-prep': typeof ExamPrepRoute
  '/mcp': typeof McpRoute
  '/plc': typeof PlcRoute
  '/practice-test': typeof PracticeTestRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-tools': typeof StudyToolsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/parse-l5x': typeof ApiParseL5xRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/courses/$trade': typeof CoursesTradeRoute
  '/dev/motor-calcs': typeof DevMotorCalcsRoute
  '/share/$token': typeof ShareTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-center': typeof DataCenterRoute
  '/exam-prep': typeof ExamPrepRoute
  '/mcp': typeof McpRoute
  '/plc': typeof PlcRoute
  '/practice-test': typeof PracticeTestRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-tools': typeof StudyToolsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/parse-l5x': typeof ApiParseL5xRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/courses/$trade': typeof CoursesTradeRoute
  '/dev/motor-calcs': typeof DevMotorCalcsRoute
  '/share/$token': typeof ShareTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-center'
    | '/exam-prep'
    | '/mcp'
    | '/plc'
    | '/practice-test'
    | '/profile'
    | '/sitemap.xml'
    | '/study-tools'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/parse-l5x'
    | '/course/$courseId'
    | '/courses/$trade'
    | '/dev/motor-calcs'
    | '/share/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-center'
    | '/exam-prep'
    | '/mcp'
    | '/plc'
    | '/practice-test'
    | '/profile'
    | '/sitemap.xml'
    | '/study-tools'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/parse-l5x'
    | '/course/$courseId'
    | '/courses/$trade'
    | '/dev/motor-calcs'
    | '/share/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/share/$token'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/data-center'
    | '/exam-prep'
    | '/mcp'
    | '/plc'
    | '/practice-test'
    | '/profile'
    | '/sitemap.xml'
    | '/study-tools'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/parse-l5x'
    | '/course/$courseId'
    | '/courses/$trade'
    | '/dev/motor-calcs'
    | '/share/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DataCenterRoute: typeof DataCenterRoute
  ExamPrepRoute: typeof ExamPrepRoute
  McpRoute: typeof McpRoute
  PlcRoute: typeof PlcRoute
  PracticeTestRoute: typeof PracticeTestRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyToolsRoute: typeof StudyToolsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiParseL5xRoute: typeof ApiParseL5xRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  CoursesTradeRoute: typeof CoursesTradeRoute
  DevMotorCalcsRoute: typeof DevMotorCalcsRoute
  ShareTokenRoute: typeof ShareTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicShareTokenRoute: typeof ApiPublicShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-tools': {
      id: '/study-tools'
      path: '/study-tools'
      fullPath: '/study-tools'
      preLoaderRoute: typeof StudyToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-test': {
      id: '/practice-test'
      path: '/practice-test'
      fullPath: '/practice-test'
      preLoaderRoute: typeof PracticeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plc': {
      id: '/plc'
      path: '/plc'
      fullPath: '/plc'
      preLoaderRoute: typeof PlcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-prep': {
      id: '/exam-prep'
      path: '/exam-prep'
      fullPath: '/exam-prep'
      preLoaderRoute: typeof ExamPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-center': {
      id: '/data-center'
      path: '/data-center'
      fullPath: '/data-center'
      preLoaderRoute: typeof DataCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/motor-calcs': {
      id: '/dev/motor-calcs'
      path: '/dev/motor-calcs'
      fullPath: '/dev/motor-calcs'
      preLoaderRoute: typeof DevMotorCalcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$trade': {
      id: '/courses/$trade'
      path: '/courses/$trade'
      fullPath: '/courses/$trade'
      preLoaderRoute: typeof CoursesTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-l5x': {
      id: '/api/parse-l5x'
      path: '/api/parse-l5x'
      fullPath: '/api/parse-l5x'
      preLoaderRoute: typeof ApiParseL5xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share/$token': {
      id: '/api/public/share/$token'
      path: '/api/public/share/$token'
      fullPath: '/api/public/share/$token'
      preLoaderRoute: typeof ApiPublicShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DataCenterRoute: DataCenterRoute,
  ExamPrepRoute: ExamPrepRoute,
  McpRoute: McpRoute,
  PlcRoute: PlcRoute,
  PracticeTestRoute: PracticeTestRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyToolsRoute: StudyToolsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiParseL5xRoute: ApiParseL5xRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  CoursesTradeRoute: CoursesTradeRoute,
  DevMotorCalcsRoute: DevMotorCalcsRoute,
  ShareTokenRoute: ShareTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicShareTokenRoute: ApiPublicShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
